currencies = [
  {"code":"AUD","symbol":"$","name":"Australian dollar"},
  {"code":"BGN","symbol":"BGN","name":"Bulgarian lev"},
  {"code":"BYR","symbol":"Br","name":"Belarusian ruble"},
  {"code":"BYN","symbol":"Br","name":"Belarusian ruble"},
  {"code":"CAD","symbol":"$","name":"Canadian dollar"},
  {"code":"CHF","symbol":"Fr.","name":"Swiss franc"},
  {"code":"CNY","symbol":"\u00a5","name":"Chinese/Yuan renminbi"},
  {"code":"CZK","symbol":"K\u010d","name":"Czech koruna"},
  {"code":"DKK","symbol":"Kr","name":"Danish krone"},
  {"code":"EUR","symbol":"\u20ac","name":"European Euro"},
  {"code":"GBP","symbol":"\u00a3","name":"British pound"},
  {"code":"IRR","symbol":"IRR","name":"Iranian rial"},
  {"code":"ISK","symbol":"kr","name":"Icelandic kr\u00f3na"},
  {"code":"JPY","symbol":"\u00a5","name":"Japanese yen"},
  {"code":"KGS","symbol":"\u0441\u043e\u043c","name":"Kyrgyzstani som"},
  {"code":"KWD","symbol":"KWD","name":"Kuwaiti dinar"},
  {"code":"KZT","symbol":"T","name":"Kazakhstani tenge"},
  {"code":"MDL","symbol":"MDL","name":"Moldovan leu"},
  {"code":"NOK","symbol":"kr","name":"Norwegian krone"},
  {"code":"NZD","symbol":"NZ$","name":"New Zealand dollar"},
  {"code":"PLN","symbol":"z\u0142","name":"Polish zloty"},
  {"code":"RUB","symbol":"R","name":"Russian ruble"},
  {"code":"SEK","symbol":"kr","name":"Swedish krona"},
  {"code":"SGD","symbol":"S$","name":"Singapore dollar"},
  {"code":"TRY","symbol":"TRY","name":"Turkish new lira"},
  {"code":"UAH","symbol":"UAH","name":"Ukrainian hryvnia"},
  {"code":"USD","symbol":"US$","name":"United States dollar"},
  {"code":"XDR","symbol":"SDR","name":"Special Drawing Rights"}
];

defaultCurrency = "USD";