if (Currencies.find().count() === 0) {
    Currencies.insert({'code': 'AED', 'symbol': '\u062f.\u0625;', 'name': 'UAE dirham', 'enable': true}),
    Currencies.insert({'code': 'AFN', 'symbol': 'Afs', 'name': 'Afghan afghani', 'enable': true}),
    Currencies.insert({'code': 'ALL', 'symbol': 'L', 'name': 'Albanian lek', 'enable': true}),
    Currencies.insert({'code': 'AMD', 'symbol': 'AMD', 'name': 'Armenian dram', 'enable': true}),
    Currencies.insert({'code': 'ANG', 'symbol': 'NA\u0192', 'name': 'Netherlands Antillean gulden', 'enable': true}),
    Currencies.insert({'code': 'AOA', 'symbol': 'Kz', 'name': 'Angolan kwanza', 'enable': true}),
    Currencies.insert({'code': 'ARS', 'symbol': '$', 'name': 'Argentine peso', 'enable': true}),
    Currencies.insert({'code': 'AUD', 'symbol': '$', 'name': 'Australian dollar', 'enable': true}),
    Currencies.insert({'code': 'AWG', 'symbol': '\u0192', 'name': 'Aruban florin', 'enable': true}),
    Currencies.insert({'code': 'AZN', 'symbol': 'AZN', 'name': 'Azerbaijani manat', 'enable': true}),
    Currencies.insert({'code': 'BAM', 'symbol': 'KM', 'name': 'Bosnia and Herzegovina konvertibilna marka', 'enable': true}),
    Currencies.insert({'code': 'BBD', 'symbol': 'Bds$', 'name': 'Barbadian dollar', 'enable': true}),
    Currencies.insert({'code': 'BDT', 'symbol': '\u09f3', 'name': 'Bangladeshi taka', 'enable': true}),
    Currencies.insert({'code': 'BGN', 'symbol': 'BGN', 'name': 'Bulgarian lev', 'enable': true}),
    Currencies.insert({'code': 'BHD', 'symbol': '.\u062f.\u0628', 'name': 'Bahraini dinar', 'enable': true}),
    Currencies.insert({'code': 'BIF', 'symbol': 'FBu', 'name': 'Burundi franc', 'enable': true}),
    Currencies.insert({'code': 'BMD', 'symbol': 'BD$', 'name': 'Bermudian dollar', 'enable': true}),
    Currencies.insert({'code': 'BND', 'symbol': 'B$', 'name': 'Brunei dollar', 'enable': true}),
    Currencies.insert({'code': 'BOB', 'symbol': 'Bs.', 'name': 'Bolivian boliviano', 'enable': true}),
    Currencies.insert({'code': 'BRL', 'symbol': 'R$', 'name': 'Brazilian real', 'enable': true}),
    Currencies.insert({'code': 'BSD', 'symbol': 'B$', 'name': 'Bahamian dollar', 'enable': true}),
    Currencies.insert({'code': 'BTN', 'symbol': 'Nu.', 'name': 'Bhutanese ngultrum', 'enable': true}),
    Currencies.insert({'code': 'BWP', 'symbol': 'P', 'name': 'Botswana pula', 'enable': true}),
    Currencies.insert({'code': 'BYR', 'symbol': 'Br', 'name': 'Belarusian ruble', 'enable': true}),
    Currencies.insert({'code': 'BZD', 'symbol': 'BZ$', 'name': 'Belize dollar', 'enable': true}),
    Currencies.insert({'code': 'CAD', 'symbol': '$', 'name': 'Canadian dollar', 'enable': true}),
    Currencies.insert({'code': 'CDF', 'symbol': 'F', 'name': 'Congolese franc', 'enable': true}),
    Currencies.insert({'code': 'CHF', 'symbol': 'Fr.', 'name': 'Swiss franc', 'enable': true}),
    Currencies.insert({'code': 'CLP', 'symbol': '$', 'name': 'Chilean peso', 'enable': true}),
    Currencies.insert({'code': 'CNY', 'symbol': '\u00a5', 'name': 'Chinese/Yuan renminbi', 'enable': true}),
    Currencies.insert({'code': 'COP', 'symbol': 'Col$', 'name': 'Colombian peso', 'enable': true}),
    Currencies.insert({'code': 'CRC', 'symbol': '\u20a1', 'name': 'Costa Rican colon', 'enable': true}),
    Currencies.insert({'code': 'CUC', 'symbol': '$', 'name': 'Cuban peso', 'enable': true}),
    Currencies.insert({'code': 'CVE', 'symbol': 'Esc', 'name': 'Cape Verdean escudo', 'enable': true}),
    Currencies.insert({'code': 'CZK', 'symbol': 'K\u010d', 'name': 'Czech koruna', 'enable': true}),
    Currencies.insert({'code': 'DJF', 'symbol': 'Fdj', 'name': 'Djiboutian franc', 'enable': true}),
    Currencies.insert({'code': 'DKK', 'symbol': 'Kr', 'name': 'Danish krone', 'enable': true}),
    Currencies.insert({'code': 'DOP', 'symbol': 'RD$', 'name': 'Dominican peso', 'enable': true}),
    Currencies.insert({'code': 'DZD', 'symbol': '\u062f.\u062c', 'name': 'Algerian dinar', 'enable': true}),
    Currencies.insert({'code': 'EEK', 'symbol': 'KR', 'name': 'Estonian kroon', 'enable': true}),
    Currencies.insert({'code': 'EGP', 'symbol': '\u00a3', 'name': 'Egyptian pound', 'enable': true}),
    Currencies.insert({'code': 'ERN', 'symbol': 'Nfa', 'name': 'Eritrean nakfa', 'enable': true}),
    Currencies.insert({'code': 'ETB', 'symbol': 'Br', 'name': 'Ethiopian birr', 'enable': true}),
    Currencies.insert({'code': 'EUR', 'symbol': '\u20ac', 'name': 'European Euro', 'enable': true}),
    Currencies.insert({'code': 'FJD', 'symbol': 'FJ$', 'name': 'Fijian dollar', 'enable': true}),
    Currencies.insert({'code': 'FKP', 'symbol': '\u00a3', 'name': 'Falkland Islands pound', 'enable': true}),
    Currencies.insert({'code': 'GBP', 'symbol': '\u00a3', 'name': 'British pound', 'enable': true}),
    Currencies.insert({'code': 'GEL', 'symbol': 'GEL', 'name': 'Georgian lari', 'enable': true}),
    Currencies.insert({'code': 'GHS', 'symbol': 'GH\u20b5', 'name': 'Ghanaian cedi', 'enable': true}),
    Currencies.insert({'code': 'GIP', 'symbol': '\u00a3', 'name': 'Gibraltar pound', 'enable': true}),
    Currencies.insert({'code': 'GMD', 'symbol': 'D', 'name': 'Gambian dalasi', 'enable': true}),
    Currencies.insert({'code': 'GNF', 'symbol': 'FG', 'name': 'Guinean franc', 'enable': true}),
    Currencies.insert({'code': 'GQE', 'symbol': 'CFA', 'name': 'Central African CFA franc', 'enable': true}),
    Currencies.insert({'code': 'GTQ', 'symbol': 'Q', 'name': 'Guatemalan quetzal', 'enable': true}),
    Currencies.insert({'code': 'GYD', 'symbol': 'GY$', 'name': 'Guyanese dollar', 'enable': true}),
    Currencies.insert({'code': 'HKD', 'symbol': 'HK$', 'name': 'Hong Kong dollar', 'enable': true}),
    Currencies.insert({'code': 'HNL', 'symbol': 'L', 'name': 'Honduran lempira', 'enable': true}),
    Currencies.insert({'code': 'HRK', 'symbol': 'kn', 'name': 'Croatian kuna', 'enable': true}),
    Currencies.insert({'code': 'HTG', 'symbol': 'G', 'name': 'Haitian gourde', 'enable': true}),
    Currencies.insert({'code': 'HUF', 'symbol': 'Ft', 'name': 'Hungarian forint', 'enable': true}),
    Currencies.insert({'code': 'IDR', 'symbol': 'Rp', 'name': 'Indonesian rupiah', 'enable': true}),
    Currencies.insert({'code': 'ILS', 'symbol': '\u20aa', 'name': 'Israeli new sheqel', 'enable': true}),
    Currencies.insert({'code': 'INR', 'symbol': '\u20B9', 'name': 'Indian rupee', 'enable': true}),
    Currencies.insert({'code': 'IQD', 'symbol': '\u062f.\u0639', 'name': 'Iraqi dinar', 'enable': true}),
    Currencies.insert({'code': 'IRR', 'symbol': 'IRR', 'name': 'Iranian rial', 'enable': true}),
    Currencies.insert({'code': 'ISK', 'symbol': 'kr', 'name': 'Icelandic kr\u00f3na', 'enable': true}),
    Currencies.insert({'code': 'JMD', 'symbol': 'J$', 'name': 'Jamaican dollar', 'enable': true}),
    Currencies.insert({'code': 'JOD', 'symbol': 'JOD', 'name': 'Jordanian dinar', 'enable': true}),
    Currencies.insert({'code': 'JPY', 'symbol': '\u00a5', 'name': 'Japanese yen', 'enable': true}),
    Currencies.insert({'code': 'KES', 'symbol': 'KSh', 'name': 'Kenyan shilling', 'enable': true}),
    Currencies.insert({'code': 'KGS', 'symbol': '\u0441\u043e\u043c', 'name': 'Kyrgyzstani som', 'enable': true}),
    Currencies.insert({'code': 'KHR', 'symbol': '\u17db', 'name': 'Cambodian riel', 'enable': true}),
    Currencies.insert({'code': 'KMF', 'symbol': 'KMF', 'name': 'Comorian franc', 'enable': true}),
    Currencies.insert({'code': 'KPW', 'symbol': 'W', 'name': 'North Korean won', 'enable': true}),
    Currencies.insert({'code': 'KRW', 'symbol': 'W', 'name': 'South Korean won', 'enable': true}),
    Currencies.insert({'code': 'KWD', 'symbol': 'KWD', 'name': 'Kuwaiti dinar', 'enable': true}),
    Currencies.insert({'code': 'KYD', 'symbol': 'KY$', 'name': 'Cayman Islands dollar', 'enable': true}),
    Currencies.insert({'code': 'KZT', 'symbol': 'T', 'name': 'Kazakhstani tenge', 'enable': true}),
    Currencies.insert({'code': 'LAK', 'symbol': 'KN', 'name': 'Lao kip', 'enable': true}),
    Currencies.insert({'code': 'LBP', 'symbol': '\u00a3', 'name': 'Lebanese lira', 'enable': true}),
    Currencies.insert({'code': 'LKR', 'symbol': 'Rs', 'name': 'Sri Lankan rupee', 'enable': true}),
    Currencies.insert({'code': 'LRD', 'symbol': 'L$', 'name': 'Liberian dollar', 'enable': true}),
    Currencies.insert({'code': 'LSL', 'symbol': 'M', 'name': 'Lesotho loti', 'enable': true}),
    Currencies.insert({'code': 'LTL', 'symbol': 'Lt', 'name': 'Lithuanian litas', 'enable': true}),
    Currencies.insert({'code': 'LVL', 'symbol': 'Ls', 'name': 'Latvian lats', 'enable': true}),
    Currencies.insert({'code': 'LYD', 'symbol': 'LD', 'name': 'Libyan dinar', 'enable': true}),
    Currencies.insert({'code': 'MAD', 'symbol': 'MAD', 'name': 'Moroccan dirham', 'enable': true}),
    Currencies.insert({'code': 'MDL', 'symbol': 'MDL', 'name': 'Moldovan leu', 'enable': true}),
    Currencies.insert({'code': 'MGA', 'symbol': 'FMG', 'name': 'Malagasy ariary', 'enable': true}),
    Currencies.insert({'code': 'MKD', 'symbol': 'MKD', 'name': 'Macedonian denar', 'enable': true}),
    Currencies.insert({'code': 'MMK', 'symbol': 'K', 'name': 'Myanma kyat', 'enable': true}),
    Currencies.insert({'code': 'MNT', 'symbol': '\u20ae', 'name': 'Mongolian tugrik', 'enable': true}),
    Currencies.insert({'code': 'MOP', 'symbol': 'P', 'name': 'Macanese pataca', 'enable': true}),
    Currencies.insert({'code': 'MRO', 'symbol': 'UM', 'name': 'Mauritanian ouguiya', 'enable': true}),
    Currencies.insert({'code': 'MUR', 'symbol': 'Rs', 'name': 'Mauritian rupee', 'enable': true}),
    Currencies.insert({'code': 'MVR', 'symbol': 'Rf', 'name': 'Maldivian rufiyaa', 'enable': true}),
    Currencies.insert({'code': 'MWK', 'symbol': 'MK', 'name': 'Malawian kwacha', 'enable': true}),
    Currencies.insert({'code': 'MXN', 'symbol': '$', 'name': 'Mexican peso', 'enable': true}),
    Currencies.insert({'code': 'MYR', 'symbol': 'RM', 'name': 'Malaysian ringgit', 'enable': true}),
    Currencies.insert({'code': 'MZM', 'symbol': 'MTn', 'name': 'Mozambican metical', 'enable': true}),
    Currencies.insert({'code': 'NAD', 'symbol': 'N$', 'name': 'Namibian dollar', 'enable': true}),
    Currencies.insert({'code': 'NGN', 'symbol': '\u20a6', 'name': 'Nigerian naira', 'enable': true}),
    Currencies.insert({'code': 'NIO', 'symbol': 'C$', 'name': 'Nicaraguan c\u00f3rdoba', 'enable': true}),
    Currencies.insert({'code': 'NOK', 'symbol': 'kr', 'name': 'Norwegian krone', 'enable': true}),
    Currencies.insert({'code': 'NPR', 'symbol': 'NRs', 'name': 'Nepalese rupee', 'enable': true}),
    Currencies.insert({'code': 'NZD', 'symbol': 'NZ$', 'name': 'New Zealand dollar', 'enable': true}),
    Currencies.insert({'code': 'OMR', 'symbol': 'OMR', 'name': 'Omani rial', 'enable': true}),
    Currencies.insert({'code': 'PAB', 'symbol': 'B./', 'name': 'Panamanian balboa', 'enable': true}),
    Currencies.insert({'code': 'PEN', 'symbol': 'S/.', 'name': 'Peruvian nuevo sol', 'enable': true}),
    Currencies.insert({'code': 'PGK', 'symbol': 'K', 'name': 'Papua New Guinean kina', 'enable': true}),
    Currencies.insert({'code': 'PHP', 'symbol': '\u20b1', 'name': 'Philippine peso', 'enable': true}),
    Currencies.insert({'code': 'PKR', 'symbol': 'Rs.', 'name': 'Pakistani rupee', 'enable': true}),
    Currencies.insert({'code': 'PLN', 'symbol': 'z\u0142', 'name': 'Polish zloty', 'enable': true}),
    Currencies.insert({'code': 'PYG', 'symbol': '\u20b2', 'name': 'Paraguayan guarani', 'enable': true}),
    Currencies.insert({'code': 'QAR', 'symbol': 'QR', 'name': 'Qatari riyal', 'enable': true}),
    Currencies.insert({'code': 'RON', 'symbol': 'L', 'name': 'Romanian leu', 'enable': true}),
    Currencies.insert({'code': 'RSD', 'symbol': 'din.', 'name': 'Serbian dinar', 'enable': true}),
    Currencies.insert({'code': 'RUB', 'symbol': '\u20bd', 'name': 'Russian ruble', 'enable': true}),
    Currencies.insert({'code': 'SAR', 'symbol': 'SR', 'name': 'Saudi riyal', 'enable': true}),
    Currencies.insert({'code': 'SBD', 'symbol': 'SI$', 'name': 'Solomon Islands dollar', 'enable': true}),
    Currencies.insert({'code': 'SCR', 'symbol': 'SR', 'name': 'Seychellois rupee', 'enable': true}),
    Currencies.insert({'code': 'SDG', 'symbol': 'SDG', 'name': 'Sudanese pound', 'enable': true}),
    Currencies.insert({'code': 'SEK', 'symbol': 'kr', 'name': 'Swedish krona', 'enable': true}),
    Currencies.insert({'code': 'SGD', 'symbol': 'S$', 'name': 'Singapore dollar', 'enable': true}),
    Currencies.insert({'code': 'SHP', 'symbol': '\u00a3', 'name': 'Saint Helena pound', 'enable': true}),
    Currencies.insert({'code': 'SLL', 'symbol': 'Le', 'name': 'Sierra Leonean leone', 'enable': true}),
    Currencies.insert({'code': 'SOS', 'symbol': 'Sh.', 'name': 'Somali shilling', 'enable': true}),
    Currencies.insert({'code': 'SRD', 'symbol': '$', 'name': 'Surinamese dollar', 'enable': true}),
    Currencies.insert({'code': 'SYP', 'symbol': 'LS', 'name': 'Syrian pound', 'enable': true}),
    Currencies.insert({'code': 'SZL', 'symbol': 'E', 'name': 'Swazi lilangeni', 'enable': true}),
    Currencies.insert({'code': 'THB', 'symbol': '\u0e3f', 'name': 'Thai baht', 'enable': true}),
    Currencies.insert({'code': 'TJS', 'symbol': 'TJS', 'name': 'Tajikistani somoni', 'enable': true}),
    Currencies.insert({'code': 'TMT', 'symbol': 'm', 'name': 'Turkmen manat', 'enable': true}),
    Currencies.insert({'code': 'TND', 'symbol': 'DT', 'name': 'Tunisian dinar', 'enable': true}),
    Currencies.insert({'code': 'TRY', 'symbol': 'TRY', 'name': 'Turkish new lira', 'enable': true}),
    Currencies.insert({'code': 'TTD', 'symbol': 'TT$', 'name': 'Trinidad and Tobago dollar', 'enable': true}),
    Currencies.insert({'code': 'TWD', 'symbol': 'NT$', 'name': 'New Taiwan dollar', 'enable': true}),
    Currencies.insert({'code': 'TZS', 'symbol': 'TZS', 'name': 'Tanzanian shilling', 'enable': true}),
    Currencies.insert({'code': 'UAH', 'symbol': 'UAH', 'name': 'Ukrainian hryvnia', 'enable': true}),
    Currencies.insert({'code': 'UGX', 'symbol': 'USh', 'name': 'Ugandan shilling', 'enable': true}),
    Currencies.insert({'code': 'USD', 'symbol': 'US$', 'name': 'United States dollar', 'enable': true}),
    Currencies.insert({'code': 'UYU', 'symbol': '$U', 'name': 'Uruguayan peso', 'enable': true}),
    Currencies.insert({'code': 'UZS', 'symbol': 'UZS', 'name': 'Uzbekistani som', 'enable': true}),
    Currencies.insert({'code': 'VEB', 'symbol': 'Bs', 'name': 'Venezuelan bolivar', 'enable': true}),
    Currencies.insert({'code': 'VND', 'symbol': '\u20ab', 'name': 'Vietnamese dong', 'enable': true}),
    Currencies.insert({'code': 'VUV', 'symbol': 'VT', 'name': 'Vanuatu vatu', 'enable': true}),
    Currencies.insert({'code': 'WST', 'symbol': 'WS$', 'name': 'Samoan tala', 'enable': true}),
    Currencies.insert({'code': 'XAF', 'symbol': 'CFA', 'name': 'Central African CFA franc', 'enable': true}),
    Currencies.insert({'code': 'XCD', 'symbol': 'EC$', 'name': 'East Caribbean dollar', 'enable': true}),
    Currencies.insert({'code': 'XDR', 'symbol': 'SDR', 'name': 'Special Drawing Rights', 'enable': true}),
    Currencies.insert({'code': 'XOF', 'symbol': 'CFA', 'name': 'West African CFA franc', 'enable': true}),
    Currencies.insert({'code': 'XPF', 'symbol': 'F', 'name': 'CFP franc', 'enable': true}),
    Currencies.insert({'code': 'YER', 'symbol': 'YER', 'name': 'Yemeni rial', 'enable': true}),
    Currencies.insert({'code': 'ZAR', 'symbol': 'R', 'name': 'South African rand', 'enable': true}),
    Currencies.insert({'code': 'ZMK', 'symbol': 'ZK', 'name': 'Zambian kwacha', 'enable': true}),
    Currencies.insert({'code': 'ZWR', 'symbol': 'Z$', 'name': 'Zimbabwean dollar'})
}
    